print("- Hello! What is your name?")
name = input("> ")
print("- I'm glad to see you", name, "!")
print("- What is your age?")
age = int(input("> "))
print("- I thought you are", age + 1, "years old. You look younger!")